AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for API Gateway with HTTP GET Integration

Parameters:
  UsernameQueryParam:
    Type: String
    Description: Query parameter value for the 'username' parameter

Resources:
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: GitServiceAPI

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: "{proxy+}"

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: GET
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: "200"
      Integration:
        Type: HTTP
        IntegrationHttpMethod: GET
        Uri: !Sub "http://git-service-lb-935973025.eu-north-1.elb.amazonaws.com/repos?username=${UsernameQueryParam}"
        IntegrationResponses:
          - StatusCode: "200"
            ResponseTemplates:
              application/json: ""
        PassthroughBehavior: WHEN_NO_MATCH

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi

